server:
  port: 9501

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://admin:admin@eureka1:7001/eureka
    register-with-eureka: false

spring:
  application:
    name:  springcloud-zuul
  security:
      user:
        name: admin
        password: admin

zuul:
  routes:
    springcloud-provider-product:  /product-proxy/**
  ignored-services:
      "*"


#zuul:
  #routes:
    #users:
      #path: /users-proxy/**
      #serviceId: microcloud-provider-users
    #users2:
      #path: /users2-proxy/**
      #url: http://localhost:8090/
    #product:
      #path: /product-proxy/**
      #serviceId: microcloud-provider-product
  #ignored-services:
    #"*"
  #prefix: /enjoy-api